### ISSUE TITLE
Exception occurs when client computer falls asleep (hibernates?)

### ISSUE THREAD

**Issue by transistor1** [Field-Effect-LLC/RDP-BattMon#18]
When computer is closed & hibernates, exception occurs

```
2018-03-10 14:51:34,420 [8] FATAL FieldEffect.Program [(null)] - FieldEffect.VCL.Exceptions.VirtualChannelException: TsClientAddIn (BATTMON): Couldn't write to communcation channel for battery monitor.
   at FieldEffect.VCL.Client.RdpClientVirtualChannel.VirtualChannelWrite(Byte[] data) in C:\Users\russosv\Documents\Visual Studio 2017\Projects\RDP Laptop Battery Monitor\RDP Virtual Channel Library\Client\RdpClientVirtualChannel.cs:line 60
   at FieldEffect.Models.BatteryDataReporter._clientAddIn_DataChannelEvent(Object sender, DataChannelEventArgs e) in C:\Users\russosv\Documents\Visual Studio 2017\Projects\RDP Laptop Battery Monitor\Client MSTSC Add-in\Models\BatteryDataReporter.cs:line 87
   at FieldEffect.VCL.Client.RdpClientVirtualChannel.OnDataChannelEvent(DataChannelEventArgs e) in C:\Users\russosv\Documents\Visual Studio 2017\Projects\RDP Laptop Battery Monitor\RDP Virtual Channel Library\Client\RdpClientVirtualChannel.cs:line 100
   at FieldEffect.VCL.Client.RdpClientVirtualChannel.VirtualChannelOpenEvent(Int32 openHandle, ChannelEvents Event, Byte[] data, Int32 dataLength, UInt32 totalLength, ChannelFlags dataFlags) in C:\Users\russosv\Documents\Visual Studio 2017\Projects\RDP Laptop Battery Monitor\RDP Virtual Channel Library\Client\RdpClientVirtualChannel.cs:line 117

```

**Comment by transistor1** [comment]
Fixed - needs testing

**Comment by peterberbec** [comment]
I'll help. Does the problem occur when the client or host sleeps?

**Comment by transistor1** [comment]
I noticed that it happened when the client sleeps.  Fixing title

**Comment by peterberbec** [comment]
Ok. Is there a binary for testing? (sorry no VS)

**Comment by peterberbec** [comment]
Tried sleeping using 1.0.2 and I didn't get any errors.

**Comment by transistor1** [comment]
Sure -- here you go; thanks!  More info: I left the server component (tray icon) running on my remote desktop, put my Surface to sleep & left for the day.

When I came back, the computer had gone into a deep sleep (come to think of it, I think it was actually hibernating -- completely off), and the client had crashed with the stack trace in the top post.

[BattMon v1.0.2.1 Client+Server (Debug).zip](https://github.com/Field-Effect-LLC/RDP-BattMon/files/1799985/BattMon.v1.0.2.1.Client.Server.Debug.zip)

**Comment by peterberbec** [comment]
Just hibernated. took 2 seconds for RDP to reconnect then 2 more seconds for battery info to populate.

I'll try sleeping again.

**Comment by peterberbec** [comment]
Sleeping didn't do anything either.

Possibly sleeping then going into hibernate then waking up?

**Comment by peterberbec** [comment]
Set my PC to sleep after 1 minute and hibernate after 2 minutes. I'll check back in about 5.

**Comment by transistor1** [comment]
It might be a sporadic issue.  Since the server component is polling the client for battery status, I think it might have to fall asleep at just the right time (when the VirtualChannelWrite gets called, to respond to the polling).

I've seen the crash happen several times before, but this is the first time I caught the stack trace.

**Comment by transistor1** [comment]
FWIW, polling happens once every 10 sec.

**Comment by peterberbec** [comment]
Didn't get a crash even sleep to hibernate.

**Comment by transistor1** [comment]
Oh well.. Maybe it's only happening on my machine.  Don't worry too much about it -- I put a try/catch with logging on the line where the exception is occurring, so I think that should be good.  If not, I'll know about it soon enough.

Thanks for the help & don't forget to "spring ahead" tonight if you're in a daylight savings time area in the US (I am!)

**Comment by peterberbec** [comment]
Grumble grumble. I'm going to demand my hour of sleep back from the next farmer I meet.

**Comment by transistor1** [comment]
Confirmed fixed.  It now appears as a warning in the log, but it doesn't crash the client.

```
2018-03-11 19:44:55,175 [7] WARN  FieldEffect.Models.BatteryDataReporter [(null)] - FieldEffect.VCL.Exceptions.VirtualChannelException: TsClientAddIn (BATTMON): Couldn't write to communcation channel for battery monitor.
   at FieldEffect.VCL.Client.RdpClientVirtualChannel.VirtualChannelWrite(Byte[] data) in C:\Users\russosv\Documents\Visual Studio 2017\Projects\RDP Laptop Battery Monitor\RDP Virtual Channel Library\Client\RdpClientVirtualChannel.cs:line 60
   at FieldEffect.Models.BatteryDataReporter._clientAddIn_DataChannelEvent(Object sender, DataChannelEventArgs e) in C:\Users\russosv\Documents\Visual Studio 2017\Projects\RDP Laptop Battery Monitor\Client MSTSC Add-in\Models\BatteryDataReporter.cs:line 91

```
